/**
 * The non-engine flow-vs-solid crossings that remain after phase 1, each with its deepest penetration of the
 * rendered tube surface into the solid (mm) and why it is accepted. Shrink-only, like the skin-containment DEBT ledger:
 * tests/sr22t-flow-crossings.test.ts fails on a crossing missing here, on one deeper than its entry, and on an entry
 * whose crossing is gone (delete it). The operator accepts these as schematic overlap (ruling of 2026-10-08).
 * - pass: the line passes through structure or a panel it must cross (spar, firewall, bulkhead, instrument panel, rib);
 * - enclosure: the line runs inside the console or panel enclosure that holds its connector or valve;
 * - host: an inline node of the flow itself (valve, water trap, sump, sensor, collector, avionics unit);
 * - cable: a control cable through its own guide hardware (fairlead, turnbuckle, clamp, pulley bracket, bridle);
 * - overlap: accepted schematic overlap, left for a later pass.
 */
export type Why = "pass" | "enclosure" | "host" | "cable" | "overlap";
export const CROSSINGS: Record<string, [mm: number, why: Why]> = {
  "acCoupler / Main spar": [47.7, "pass"],
  "acDischarge / Receiver-drier": [7.0, "overlap"],
  "acEvapDuct / Main spar": [48.4, "pass"],
  "ailBal / Aileron cable fairlead": [14.7, "cable"],
  "ailBal / Aileron turnbuckle": [13.4, "cable"],
  "ailBal / Filter assembly": [2.7, "overlap"],
  "ailL / Aileron cable fairlead": [14.5, "cable"],
  "ailL / Aileron turnbuckle": [11.6, "cable"],
  "ailL / Bridle cable clamp": [9.2, "cable"],
  "ailL / Filter assembly": [1.2, "overlap"],
  "ailL / Roll servo bridle cable": [4.6, "cable"],
  "ailR / Aileron cable fairlead": [14.5, "cable"],
  "ailR / Aileron turnbuckle": [13.5, "cable"],
  "ailR / Brake valve line (R)": [6.4, "overlap"],
  "ailR / Bridle cable clamp": [9.3, "cable"],
  "ailR / Roll servo bridle cable": [4.5, "cable"],
  "armL / Floor butterfly valve": [14.6, "host"],
  "armL / Forward harness strap": [11.6, "overlap"],
  "armR / Floor butterfly valve": [14.6, "host"],
  "armR / Forward harness strap": [11.6, "overlap"],
  "audioGia1 / Avionics panel (centre console)": [68.2, "enclosure"],
  "audioGia2 / Avionics panel (centre console)": [66.4, "enclosure"],
  "bat2 / Aft bulkhead — FS 222": [11.9, "pass"],
  "bat2 / Forward unit supply line": [14.2, "overlap"],
  "bat2 / Main spar": [47.4, "pass"],
  "defrost / Defrost butterfly valve": [20.2, "host"],
  "elA / Aft bulkhead — FS 222": [4.2, "pass"],
  "elA / Avionics panel (centre console)": [15.1, "enclosure"],
  "elA / Bridle cable clamp": [11.0, "cable"],
  "elA / Bridle clamp spacer": [4.1, "cable"],
  "elA / Elevator turnbuckle": [13.9, "cable"],
  "elA / Forward pulley gang bracket": [7.3, "cable"],
  "elA / Pitch servo bridle cable": [4.9, "cable"],
  "elA / Rudder/elevator pulley gang bracket": [10.4, "cable"],
  "elB / A/C condenser": [22.8, "overlap"],
  "elB / Aft bulkhead — FS 222": [4.1, "pass"],
  "elB / Bridle cable clamp": [11.0, "cable"],
  "elB / Bridle clamp spacer": [4.1, "cable"],
  "elB / Elevator turnbuckle": [13.9, "cable"],
  "elB / Pitch servo bridle cable": [5.4, "cable"],
  "elB / Rudder/elevator pulley gang bracket": [9.7, "cable"],
  "fanDuct / Main spar": [52.3, "pass"],
  "floorR / Brake bulkhead fitting": [7.7, "overlap"],
  "floorR / Filter assembly": [35.4, "overlap"],
  "floorR / Floor butterfly valve": [15.0, "host"],
  "floorR2 / Brake bulkhead fitting": [7.7, "overlap"],
  "floorR2 / Floor butterfly valve": [15.0, "host"],
  "fuelL / Flapper valve": [6.7, "host"],
  "fuelL / Left collector tank / sump": [47.0, "host"],
  "fuelL / Main gear strut": [7.4, "overlap"],
  "fuelL / Main gear upper attach fitting": [1.4, "overlap"],
  "fuelMain / Firewall fuel enclosure": [39.0, "pass"],
  "fuelMain / Main spar": [29.8, "pass"],
  "fuelR / Flapper valve": [6.7, "host"],
  "fuelR / Main gear strut": [7.4, "overlap"],
  "fuelR / Main gear upper attach fitting": [1.4, "overlap"],
  "fuelR / Right collector tank / sump": [47.0, "host"],
  "fuelRetL / Center console": [91.8, "enclosure"],
  "fuelRetL / Firewall fuel enclosure": [33.5, "pass"],
  "fuelRetL / Forward pulley gang bracket": [9.3, "overlap"],
  "fuelRetL / Rudder pedal torque tube": [4.2, "overlap"],
  "fuelRetL / Selector valve enclosure": [85.3, "enclosure"],
  "fuelRetR / Center console": [91.6, "enclosure"],
  "fuelRetR / Firewall fuel enclosure": [33.8, "pass"],
  "fuelRetR / Forward pulley gang bracket": [9.3, "overlap"],
  "fuelRetR / Rudder pedal torque tube": [4.3, "overlap"],
  "fuelRetR / Selector valve enclosure": [85.2, "enclosure"],
  "mfdFeedA / Avionics panel (centre console)": [65.1, "enclosure"],
  "mfdFeedB / Avionics panel (centre console)": [54.1, "enclosure"],
  "panelL2 / Instrument panel": [35.2, "pass"],
  "panelR2 / Instrument panel": [36.0, "pass"],
  "pfdFeedA / Avionics panel (centre console)": [12.0, "enclosure"],
  "pitot / Bolster switch panel": [28.4, "enclosure"],
  "pitot / Fuel baffle rib": [17.0, "pass"],
  "pitot / Instrument panel": [28.4, "pass"],
  "pitot / Main spar": [10.8, "pass"],
  "pitot / Pitot water trap": [33.7, "host"],
  "pitotAdahrs2 / Instrument panel": [11.9, "pass"],
  "rudL / Aft bulkhead — FS 222": [3.8, "pass"],
  "rudL / Receiver-drier": [18.4, "overlap"],
  "rudL / Rudder turnbuckle": [13.9, "cable"],
  "rudL / Rudder/elevator pulley gang bracket": [10.4, "cable"],
  "rudR / Aft bulkhead — FS 222": [3.9, "pass"],
  "rudR / Bridle cable clamp": [11.0, "cable"],
  "rudR / Rudder turnbuckle": [13.9, "cable"],
  "rudR / Rudder/elevator pulley gang bracket": [9.7, "cable"],
  "rudR / Yaw servo bridle cable": [5.2, "cable"],
  "stall / Fuel baffle rib": [16.3, "pass"],
  "stall / Main spar": [39.4, "pass"],
  "stall / Tail harness": [6.0, "overlap"],
  "stallWire / Fuel baffle rib": [12.8, "pass"],
  "stallWire / Main spar": [32.2, "pass"],
  "static / Static line sump (R)": [20.1, "host"],
  "static2 / Aft bulkhead — FS 222": [8.8, "pass"],
  "static2 / Brake valve line (R)": [7.0, "overlap"],
  "static2 / Center console": [19.5, "enclosure"],
  "static2 / Circuit breaker panel": [19.0, "enclosure"],
  "static2 / Forward proportioning unit": [22.3, "overlap"],
  "static2 / Forward unit supply line": [15.8, "overlap"],
  "static2 / Main spar": [14.8, "pass"],
  "static2 / Static water trap": [33.8, "host"],
  "staticAdahrs / Bolster switch panel": [23.7, "enclosure"],
  "staticAdahrs / Instrument panel": [28.5, "pass"],
  "staticAdahrs2 / Avionics panel (centre console)": [13.3, "enclosure"],
  "staticAdahrs2 / Center console": [16.6, "enclosure"],
  "staticAdahrs2 / Circuit breaker panel": [15.1, "enclosure"],
  "staticAdahrs2 / Instrument panel": [7.5, "pass"],
  "staticAlt / Circuit breaker panel": [13.0, "enclosure"],
  "staticL / Static line sump (L)": [20.6, "host"],
  "toMan / Duct temperature sensor": [46.1, "host"],
  "trafficData / GSU 75 ADAHRS 1": [48.5, "host"],
  "trafficData / MAG 1 wiring": [6.6, "host"],
  "xpdrData / Aft bulkhead — FS 222": [3.7, "pass"],
};

/** Engine-side baseline, measured with the phase-1 winding-number oracle.
 * host: inline hardware belonging to the circuit; pass: firewall penetration.
 * overlap: the optional ALT 2 routes, ruled exhaust attachments and the fixed throttle-cable fitting contact.
 * The accessory-case and free throttle approach crossings are cleared. Lead ruling: fuelMain shares its pump anchor
 * with MIXTURE_ARM; its case contact inside the unexpanded pump bounds and mixture-cable coincidence remain hosts.
 * Oil filter/adapter contacts are the oil circuit's own hardware, retained as hosts. No parts or anchors moved.
 * Depths are measured model overlaps, not aircraft dimensions. */
export const ENGINE_CROSSINGS: Record<string, [mm: number, why: Why]> = {
  "acDischarge / Firewall — FS 100": [6.3, "pass"],
  "acSuction / Firewall — FS 100": [8.0, "pass"],
  "alt2 / Cylinder 6": [8.4, "overlap"],
  "alt2 / MCU heat shield": [13.1, "overlap"],
  "alt2 / sr22t/part-204": [11.5, "overlap"],
  "altAirL / Alternate air duct": [43.2, "host"],
  "altAirR / Alternate air duct": [43.2, "host"],
  "cbEss / Firewall — FS 100": [5.0, "pass"],
  "cbMdb1 / Firewall — FS 100": [5.0, "pass"],
  "cbMdb2 / Firewall — FS 100": [5.0, "pass"],
  // Lead ruling: gas flows inside the real pipe; tie rod/blast tube attach to it. Accepted known baseline.
  "crossover / Alternate air blast tube": [29.0, "overlap"],
  "crossover / Exhaust tie rod": [1.8, "overlap"],
  "exh1 / Exhaust tie rod": [5.4, "overlap"],
  "exh3 / Exhaust tie rod": [5.4, "overlap"],
  "exh5 / Exhaust tie rod": [5.4, "overlap"],
  "crossover / Exhaust crossover / heat exchanger": [79.3, "host"],
  "crossover / Wastegate bypass pipe": [37.6, "host"],
  "crossover / Wastegate transition": [48.5, "host"],
  "deckRef / Upper-deck pressure line": [10.1, "host"],
  "exh1 / EGT probe — cyl 1": [4.2, "host"],
  "exh1 / Exhaust crossover pipe": [13.3, "host"],
  "exh1 / Exhaust slip joint": [35.6, "host"],
  "exh1 / Exhaust tee": [31.5, "host"],
  "exh1 / TIT probe — RH": [9.7, "host"],
  "exh2 / EGT probe — cyl 2": [4.2, "host"],
  "exh2 / Exhaust crossover pipe": [11.8, "host"],
  "exh2 / Exhaust slip joint": [35.6, "host"],
  "exh2 / Exhaust tee": [31.5, "host"],
  "exh2 / TIT probe — LH": [17.9, "host"],
  "exh3 / Cylinder exhaust riser": [26.3, "host"],
  "exh3 / EGT probe — cyl 3": [4.2, "host"],
  "exh3 / Exhaust crossover pipe": [13.3, "host"],
  "exh3 / Exhaust slip joint": [35.6, "host"],
  "exh3 / Exhaust tee": [31.5, "host"],
  "exh3 / TIT probe — RH": [9.8, "host"],
  "exh4 / Cylinder exhaust riser": [15.6, "host"],
  "exh4 / EGT probe — cyl 4": [4.2, "host"],
  "exh4 / Exhaust crossover pipe": [11.8, "host"],
  "exh4 / Exhaust slip joint": [35.6, "host"],
  "exh4 / Exhaust tee": [31.5, "host"],
  "exh4 / TIT probe — LH": [17.9, "host"],
  "exh5 / Cylinder exhaust riser": [26.1, "host"],
  "exh5 / EGT probe — cyl 5": [4.1, "host"],
  "exh5 / Exhaust crossover pipe": [13.3, "host"],
  "exh5 / Exhaust slip joint": [35.6, "host"],
  "exh5 / Exhaust tee": [31.5, "host"],
  "exh5 / TIT probe — RH": [9.7, "host"],
  "exh6 / Cylinder exhaust riser": [15.9, "host"],
  "exh6 / EGT probe — cyl 6": [4.2, "host"],
  "exh6 / Exhaust crossover pipe": [11.8, "host"],
  "exh6 / Exhaust slip joint": [35.6, "host"],
  "exh6 / Exhaust tee": [31.5, "host"],
  "exh6 / TIT probe — LH": [17.8, "host"],
  "fuelDrainHeads / Cylinder drain manifold check valve": [21.2, "host"],
  "fuelMain / Continental TSIO-550-K": [22.4, "host"],
  "fuelMain / Electric fuel pump": [54.0, "host"],
  "fuelMain / Engine-driven fuel pump": [57.9, "host"],
  "fuelMain / Firewall — FS 100": [13.9, "pass"],
  "fuelMain / Fuel flow transducer": [38.5, "host"],
  "fuelMain / Gascolator": [57.8, "host"],
  // the cable ends 5.5 mm from fixed THROTTLE, inside fuelMain's 14 mm tube radius.
  // Unavoidable fitting contacts stay inside the metering body's unexpanded bounds (ENGINE_FIXED).
  "fuelMain / Mixture control cable": [19.2, "host"],
  "fuelMain / Throttle body / fuel-metering valve": [63.3, "host"],
  "fuelMain / Throttle control cable": [19.4, "overlap"],
  "fuelRetL / Firewall — FS 100": [8.2, "pass"],
  "fuelRetR / Firewall — FS 100": [8.3, "pass"],
  "gateBypass / Wastegate": [50.7, "host"],
  "gateBypass / Wastegate bypass pipe": [34.5, "host"],
  "gateOil / Controller oil return": [10.3, "host"],
  "gateOil / Wastegate actuator": [17.6, "host"],
  "gateOil / Wastegate controller": [4.5, "host"],
  "gateOil / Wastegate oil line": [10.3, "host"],
  "hotIn / Exhaust crossover / heat exchanger": [31.2, "host"],
  "man1 / Intake pipe — cyl 1": [23.5, "host"],
  "man2 / Intake pipe — cyl 2": [23.5, "host"],
  "man3 / Intake pipe — cyl 3": [23.5, "host"],
  "man4 / Intake pipe — cyl 4": [23.5, "host"],
  "man5 / Intake pipe — cyl 5": [23.5, "host"],
  "man6 / Intake pipe — cyl 6": [23.5, "host"],
  "oil / Continental TSIO-550-K": [99.8, "host"],
  "oil / Oil cooler": [40.0, "host"],
  "oil / Oil filter (full-flow)": [55.3, "host"],
  "oil / Oil filter adapter": [25.0, "host"],
  "oil / Oil pump": [44.7, "host"],
  "oil / Oil suction screen": [20.9, "host"],
  "oil / Oil temperature control valve": [27.4, "host"],
  "tailpipeL / Tailpipe": [49.9, "host"],
  "tailpipeL / Turbine discharge neck": [6.5, "host"],
  "tailpipeL / Wastegate bypass pipe": [42.0, "host"],
  "tailpipeR / Tailpipe": [49.9, "host"],
  "tailpipeR / Turbine discharge neck": [6.5, "host"],
  "toMan / Airflow flapper valve": [32.5, "host"],
  "toMan / Firewall — FS 100": [29.4, "pass"],
  "turboOilL / Turbo oil check valve": [21.6, "host"],
  "turboOilL / Turbo oil tee": [14.4, "host"],
  "turboOilR / Turbo oil check valve": [21.6, "host"],
  "turboOilR / Turbo oil tee": [14.5, "host"],
  "turboScavL / Turbo oil scavenge pump": [38.0, "host"],
  "turboScavR / Turbo oil scavenge pump": [38.0, "host"],
};
